config/routes.rb
Relish::Application.routes.draw do
  resources :upcoming_releases

  resources :releases

end

app/models/release.rb
class Release < ActiveRecord::Base
  has_one :upcoming_release
  attr_accessible :branch, :description, :requester, :url
end

app/models/upcoming_release.rb
class UpcomingRelease < ActiveRecord::Base
  belongs_to :release
  attr_accessible :scheduledTime

  def as_json(options={})
    {
      :scheduledTime => self.scheduledTime,
      :release => self.release.as_json
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  # GET /releases
  # GET /releases.json
  def index
    @releases = Release.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @releases }
    end
  end

  # GET /releases/1
  # GET /releases/1.json
  def show
    @release = Release.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @release }
    end
  end

  # GET /releases/new
  # GET /releases/new.json
  def new
    @release = Release.new
    @queue = UpcomingRelease.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @release }
    end
  end

  # GET /releases/1/edit
  def edit
    @release = Release.find(params[:id])
  end

  # POST /releases
  # POST /releases.json
  def create
    @release = Release.new(params[:release])

    respond_to do |format|
      if @release.save
        format.html { redirect_to @release, notice: 'Release was successfully created.' }
        format.json { render json: @release, status: :created, location: @release }
      else
        format.html { render action: "new" }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /releases/1
  # PUT /releases/1.json
  def update
    @release = Release.find(params[:id])

    respond_to do |format|
      if @release.update_attributes(params[:release])
        format.html { redirect_to @release, notice: 'Release was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /releases/1
  # DELETE /releases/1.json
  def destroy
    @release = Release.find(params[:id])
    @release.destroy

    respond_to do |format|
      format.html { redirect_to releases_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/upcoming_releases_controller.rb
class UpcomingReleasesController < ApplicationController
  # GET /upcoming_releases
  # GET /upcoming_releases.json
  def index
    @upcoming_releases = UpcomingRelease.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @upcoming_releases }
    end
  end

  # GET /upcoming_releases/1
  # GET /upcoming_releases/1.json
  def show
    @upcoming_release = UpcomingRelease.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @upcoming_release }
    end
  end

  # GET /upcoming_releases/new
  # GET /upcoming_releases/new.json
  def new
    @upcoming_release = UpcomingRelease.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upcoming_release }
    end
  end

  # GET /upcoming_releases/1/edit
  def edit
    @upcoming_release = UpcomingRelease.find(params[:id])
  end

  # POST /upcoming_releases
  # POST /upcoming_releases.json
  def create
    releaseId = params[:upcoming_release].delete :release

    @upcoming_release = UpcomingRelease.new(params[:upcoming_release])
    @upcoming_release.release = Release.find(releaseId)

    respond_to do |format|
      if @upcoming_release.save
        format.html { redirect_to @upcoming_release, notice: 'Upcoming release was successfully created.' }
        format.json { render json: @upcoming_release, status: :created, location: @upcoming_release }
      else
        format.html { render action: "new" }
        format.json { render json: @upcoming_release.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /upcoming_releases/1
  # PUT /upcoming_releases/1.json
  def update
    @upcoming_release = UpcomingRelease.find(params[:id])

    respond_to do |format|
      if @upcoming_release.update_attributes(params[:upcoming_release])
        format.html { redirect_to @upcoming_release, notice: 'Upcoming release was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @upcoming_release.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /upcoming_releases/1
  # DELETE /upcoming_releases/1.json
  def destroy
    @upcoming_release = UpcomingRelease.find(params[:id])
    @upcoming_release.destroy

    respond_to do |format|
      format.html { redirect_to upcoming_releases_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/upcoming_releases_helper.rb
module UpcomingReleasesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Relish</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/releases/_form.html.erb
<%= form_for(@release) do |f| %>
  <% if @release.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@release.errors.count, "error") %> prohibited this release from being saved:</h2>

      <ul>
      <% @release.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :requester %><br />
    <%= f.text_field :requester %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :branch %><br />
    <%= f.text_field :branch %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/releases/edit.html.erb
<h1>Editing release</h1>

<%= render 'form' %>

<%= link_to 'Show', @release %> |
<%= link_to 'Back', releases_path %>

app/views/releases/index.html.erb
<h1>Listing releases</h1>

<table>
  <tr>
    <th>Requester</th>
    <th>Description</th>
    <th>Url</th>
    <th>Branch</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @releases.each do |release| %>
  <tr>
    <td><%= release.requester %></td>
    <td><%= release.description %></td>
    <td><%= release.url %></td>
    <td><%= release.branch %></td>
    <td><%= link_to 'Show', release %></td>
    <td><%= link_to 'Edit', edit_release_path(release) %></td>
    <td><%= link_to 'Destroy', release, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Release', new_release_path %>

app/views/releases/new.html.erb
<div data-ng-app>
<div class="row">
	<div class="span8">
		<form action="billing" method="post" class="form-horizontal form-actions" id="billingform" accept-charset="utf-8" data-ng-controller="Releases">
			<div class="control-group">
				<label for="changes" class="control-label">	
					Business Changes
				</label>
				<div class="controls">
					<textarea name="changes" type="changes" value="" id="changes"></textarea>
					<span class="help-inline">From a user's perspective, what changed?</span>
				</div>
			</div>

			<div class="control-group">
				<label for="verify" class="control-label">	
					Verification Requirements
				</label>
				<div class="controls">
					<textarea name="verify" value="" id="verify"></textarea>
					<span class="help-inline">What needs to be done to ensure the changes are correct?</span>
				</div>
			</div>

			<div class="control-group">
				<label for="pull_request" class="control-label">	
					Pull request
				</label>
				<div class="controls"><input name="pull_request" type="text" value="" id="pull_request">
				</div>
			</div>

			<div class="control-group">
				<div data-ng-repeat="date in dates">
					<div data-ng-class="{available: date.available}" class = "controls">{{ date.title }}</div>
				</div>
			</div>
			
			<div>
				<button type="submit" class="btn btn-large btn-primary">Schedule Release</button>
			</div>
		</form>
	</div>
</div>
</div>

app/views/releases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Requester:</b>
  <%= @release.requester %>
</p>

<p>
  <b>Description:</b>
  <%= @release.description %>
</p>

<p>
  <b>Url:</b>
  <%= @release.url %>
</p>

<p>
  <b>Branch:</b>
  <%= @release.branch %>
</p>


<%= link_to 'Edit', edit_release_path(@release) %> |
<%= link_to 'Back', releases_path %>

app/views/upcoming_releases/_form.html.erb
<%= form_for(@upcoming_release) do |f| %>
  <% if @upcoming_release.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upcoming_release.errors.count, "error") %> prohibited this upcoming_release from being saved:</h2>

      <ul>
      <% @upcoming_release.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :scheduledTime %><br />
    <%= f.datetime_select :scheduledTime %>
  </div>
  <div class="field">
    <%= f.label :release %><br />
    <%= f.text_field :release %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/upcoming_releases/edit.html.erb
<h1>Editing upcoming_release</h1>

<%= render 'form' %>

<%= link_to 'Show', @upcoming_release %> |
<%= link_to 'Back', upcoming_releases_path %>

app/views/upcoming_releases/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="container">

	<form class="form-inline">
	  <input type="text" class="input-small" placeholder="Email">
	  <input type="password" class="input-small" placeholder="Password">
	  <label class="checkbox">
	    <input type="checkbox"> Remember me
	  </label>
	  <button type="submit" class="btn">Sign in</button>
	</form>

    </div> <!-- /container -->
  </body>
</html>

app/views/upcoming_releases/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="container">

	<form class="form-inline">
	  <input type="text" class="input-small" placeholder="Email">
	  <input type="password" class="input-small" placeholder="Password">
	  <label class="checkbox">
	    <input type="checkbox"> Remember me
	  </label>
	  <button type="submit" class="btn">Sign in</button>
	</form>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>

  </body>
</html>

app/views/upcoming_releases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Scheduledtime:</b>
  <%= @upcoming_release.scheduledTime %>
</p>

<p>
  <b>Release:</b>
  <%= @upcoming_release.release %>
</p>


<%= link_to 'Edit', edit_upcoming_release_path(@upcoming_release) %> |
<%= link_to 'Back', upcoming_releases_path %>